name: SHORPY CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["6.0", "8.0"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies for -f ${{ matrix.dotnet-version }}
        run: dotnet restore -f ${{ matrix.dotnet-version }}

      - name: Build the solution for -f ${{ matrix.dotnet-version }}
        run: dotnet build -f ${{ matrix.dotnet-version }} --no-restore --configuration Release

      - name: Run tests for -f ${{ matrix.dotnet-version }}
        run: dotnet test -f ${{ matrix.dotnet-version }} --no-build --configuration Release