name: SHORPY CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      next_version: ${{ steps.set_next_version.outputs.next_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Install dependencies
        run: |
         npm install @semantic-release/changelog -D
         npm install @semantic-release/exec -D

      - name: Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # npx semantic-release sets the env variable NEXT_SHORPY_VERSION when a new version is released
        run: |
          npx semantic-release 
      
      - name: Set Next Version
        id: set_next_version
        run: echo "next_version=${{ env.NEXT_SHORPY_VERSION }}" >> $GITHUB_OUTPUT

      - name: Pack Nuget
        if: ${{ success() && steps.set_next_version.outputs.next_version != '' }}
        run: dotnet pack -c Release -p:Version=${{ steps.set_next_version.outputs.next_version }} -o ./artifacts
      
      - name: Extract tag of the latest release
        if: ${{ success() && steps.set_next_version.outputs.next_version != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=$(gh release view --json tagName -q '.tagName')
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Upload NuGet Package to Release
        if: ${{ success() && steps.set_next_version.outputs.next_version != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $RELEASE_TAG ./artifacts/Shorpy.${{ steps.set_next_version.outputs.next_version }}.nupkg

  publish_packages_to_repos:
        if: ${{ success() && steps.set_next_version.outputs.next_version != '' }}
        uses: ./.github/workflows/shorpy-publish-package.yml
