name: SHORPY CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Install dependencies
        run: |
         npm install @semantic-release/changelog -D
         npm install @semantic-release/exec -D

      - name: Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Pack Nuget
        if: success() && env.NEXT_SHORPY_VERSION != ''
        run: echo $NEXT_SHORPY_VERSION | dotnet pack -c Release -p:Version=$NEXT_SHORPY_VERSION -o ./artifacts

      - name: Extract upload URL
        id: upload_url
        run: |
          UPLOAD_URL=$(gh release view --json uploadUrl -q '.uploadUrl')
          echo "UPLOAD_URL=$UPLOAD_URL" >> $GITHUB_ENV

      - name: Upload NuGet Package to Release
        if: success() && env.NEXT_SHORPY_VERSION != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./artifacts/*.nupkg
          asset_name: Shorpy.${{ env.NEXT_SHORPY_VERSION }}.nupkg
          asset_content_type: application/zip
