name: SHORPY PUBLISH PACKAGE

on:
  workflow_dispatch:
  workflow_run:
    workflows: [SHORPY CI]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifact
        run: gh release download --pattern '*.nupkg' -D './package'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with GitHub Packages
        run: |
         dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}  --source "https://nuget.pkg.github.com/Udara-de-Silva/index.json"
