name: SHORPY CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Install dependencies
        run: npm install @semantic-release/changelog -D

      - name: Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release | tee version.txt
          echo "VERSION=$(cat version.txt | grep -oP '(?<=Published version ).*')" >> $GITHUB_ENV

      - name: Pack Nuget
        if: success() && env.VERSION != ''
        run: dotnet pack -c Release -p:Version=env.VERSION -o ./artifacts

      - name: Upload NuGet Package to Release
        if: success() && env.VERSION != ''
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./artifacts/*.nupkg
          asset_name: MyProject.${{ env.VERSION }}.nupkg
          asset_content_type: application/zip
