name: SHORPY CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release

      - name: Install dependencies
        run: |
         npm install @semantic-release/changelog -D
         npm install @semantic-release/exec -D

      - name: Semantic Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release

      - name: Pack Nuget
        if: success() && env.NEXT_SHORPY_VERSION != ''
        run: dotnet pack -c Release -p:Version=$NEXT_SHORPY_VERSION -o ./artifacts
      
      - name: Extract tag of the latest release
        if: success() && env.NEXT_SHORPY_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG=$(gh release view --json tagName -q '.tagName')
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Upload NuGet Package to Release
        if: success() && env.NEXT_SHORPY_VERSION != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload $RELEASE_TAG ./artifacts/Shorpy.${{ env.NEXT_SHORPY_VERSION }}.nupkg
